plugins {
    id 'java'
    id "io.freefair.lombok" version "9.2.0"
    id "run.halo.plugin.devtools" version "0.8.0"
}

group 'run.halo.imagestream'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('run.halo.tools.platform:plugin:2.26.0')
    compileOnly 'run.halo.app:api'
    compileOnly 'run.halo.mcpserver:api:1.0.0'

    testImplementation 'run.halo.app:api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'run.halo.mcpserver:api:1.0.0'
    testRuntimeOnly 'run.halo.mcpserver:api:1.0.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

tasks.named('processResources') {
    exclude 'console/**'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.register('processUiResources', Copy) {
    from project(':ui').layout.buildDirectory.dir('dist')
    into layout.buildDirectory.dir('resources/main/ui')
    dependsOn project(':ui').tasks.named('assemble')
    shouldRunAfter tasks.named('processResources')
}

tasks.named('classes') {
    dependsOn tasks.named('processUiResources')
}

tasks.register('generateApiKeysFile') {
    def outputDir = layout.buildDirectory.dir("resources/main").get().asFile
    def apiKeysFile = file("$outputDir/apiKeys.properties")

    doLast {
        if (!outputDir.exists()) {
            outputDir.mkdirs()
        }
        def unsplashApiKey = System.getenv('UNSPLASH_API_KEY') ?: project.findProperty('unsplashApiKey') ?: ""
        def pexelsApiKey = System.getenv('PEXELS_API_KEY') ?: project.findProperty('pexelsApiKey') ?: ""
        def pixabayApiKey = System.getenv('PIXABAY_API_KEY') ?: project.findProperty('pixabayApiKey') ?: ""
        apiKeysFile.withWriter('UTF-8') { writer ->
            writer.writeLine("unsplash=$unsplashApiKey")
            writer.writeLine("pexels=$pexelsApiKey")
            writer.writeLine("pixabay=$pixabayApiKey")
        }

        println "API keys properties file generated at: $apiKeysFile"
    }
}

tasks.named("jar").configure {
    dependsOn("generateApiKeysFile")
}

tasks.named('generatePluginComponentsIdx') {
    notCompatibleWithConfigurationCache('This task invokes "Task.project" at execution time, which is not supported with configuration cache.')
}

halo {
    version = '2.26'
}

haloPlugin {
    openApi {
        groupingRules {
            extensionApis {
                displayName = 'Extension API for Image Stream Plugin'
                pathsToMatch = [
                    '/apis/unsplash.halo.run/v1alpha1/**',
                    '/apis/pexels.halo.run/v1alpha1/**',
                    '/apis/pixabay.halo.run/v1alpha1/**'
                ]
            }
        }
        groupedApiMappings = [
            '/v3/api-docs/extensionApis': 'extensionApis.json'
        ]
        generator {
            outputDir = file("${projectDir}/ui/src/api/generated")
        }
    }
}
